# Generated by Django 4.2.20 on 2025-08-02 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_options_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilmusico',
            options={'verbose_name': 'Perfil de Músico', 'verbose_name_plural': 'Perfiles de Músicos'},
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='disponibilidad',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='estilo_musical',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='experiencia_años',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='portafolio_url',
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='años_experiencia',
            field=models.PositiveIntegerField(default=1, help_text='Número de años tocando música', verbose_name='Años de experiencia'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='biografia',
            field=models.TextField(blank=True, help_text='Cuéntanos sobre tu trayectoria musical (máx. 1000 caracteres)', max_length=1000),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='disponible_para_gigs',
            field=models.BooleanField(default=True, verbose_name='Disponible para presentaciones'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='formacion_musical',
            field=models.TextField(blank=True, help_text='Estudios musicales, cursos, talleres, etc.', max_length=500, verbose_name='Formación musical'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='foto_portada',
            field=models.ImageField(blank=True, help_text='Foto principal para tu portafolio', null=True, upload_to='portafolios/fotos/', verbose_name='Foto de portada'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='generos_musicales',
            field=models.CharField(default='rock', help_text='Géneros musicales que interpretas (separados por comas)', max_length=200, verbose_name='Géneros musicales'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='instrumentos_secundarios',
            field=models.CharField(blank=True, help_text='Otros instrumentos que tocas (separados por comas)', max_length=200, verbose_name='Instrumentos secundarios'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='nivel_experiencia',
            field=models.CharField(choices=[('principiante', 'Principiante (0-2 años)'), ('intermedio', 'Intermedio (3-5 años)'), ('avanzado', 'Avanzado (6-10 años)'), ('profesional', 'Profesional (10+ años)')], default='principiante', max_length=20, verbose_name='Nivel de experiencia'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='perfil_publico',
            field=models.BooleanField(default=True, help_text='¿Deseas que tu perfil sea visible públicamente?', verbose_name='Perfil público'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='soundcloud_url',
            field=models.URLField(blank=True, verbose_name='SoundCloud'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='spotify_url',
            field=models.URLField(blank=True, verbose_name='Spotify'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='tarifa_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarifa base por presentación (opcional)', max_digits=10, null=True, verbose_name='Tarifa base'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='video_demo',
            field=models.URLField(blank=True, help_text='Enlace a video demo (YouTube, Vimeo, etc.)', verbose_name='Video demostración'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='website_personal',
            field=models.URLField(blank=True, verbose_name='Sitio web personal'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='perfilmusico',
            name='instrumento_principal',
            field=models.CharField(choices=[('guitarra', 'Guitarra'), ('bajo', 'Bajo'), ('bateria', 'Batería'), ('piano', 'Piano'), ('teclados', 'Teclados'), ('violin', 'Violín'), ('saxofon', 'Saxofón'), ('trompeta', 'Trompeta'), ('flauta', 'Flauta'), ('voz', 'Voz/Canto'), ('armonica', 'Armónica'), ('ukulele', 'Ukulele'), ('mandolina', 'Mandolina'), ('acordeon', 'Acordeón'), ('otro', 'Otro')], default='guitarra', max_length=50, verbose_name='Instrumento principal'),
        ),
        migrations.AlterField(
            model_name='perfilmusico',
            name='ubicacion',
            field=models.CharField(default='No especificada', max_length=100, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='perfilmusico',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_musico', to=settings.AUTH_USER_MODEL),
        ),
    ]
