# Generated by Django 4.2.20 on 2025-08-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_perfilmusico_options_remove_perfilmusico_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilmusico',
            name='tarifa_base',
            field=models.PositiveIntegerField(blank=True, help_text='Tarifa base por presentación en pesos chilenos (CLP)', null=True, verbose_name='Tarifa base (CLP)'),
        ),
    ]
