# Generated by Django 4.2.20 on 2025-08-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_perfilmusico_tarifa_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilmusico',
            name='foto_portada',
        ),
    ]
