# Generated by Django 4.2.20 on 2025-08-04 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_eliminar_foto_portada_duplicada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilempleador',
            options={'verbose_name': 'Perfil de Empleador', 'verbose_name_plural': 'Perfiles de Empleadores'},
        ),
        migrations.AddField(
            model_name='perfilempleador',
            name='año_fundacion',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de fundación'),
        ),
        migrations.AddField(
            model_name='perfilempleador',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Describe tu organización (máx. 1000 caracteres)', max_length=1000, verbose_name='Descripción de la organización'),
        ),
        migrations.AddField(
            model_name='perfilempleador',
            name='direccion_completa',
            field=models.TextField(blank=True, max_length=300, verbose_name='Dirección completa'),
        ),
        migrations.AddField(
            model_name='perfilempleador',
            name='email_corporativo',
            field=models.EmailField(blank=True, help_text='Email oficial de la organización (opcional)', max_length=254, verbose_name='Email corporativo'),
        ),
        migrations.AddField(
            model_name='perfilempleador',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='perfilempleador',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfilempleador',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='perfilempleador',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='perfilempleador',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='perfilempleador',
            name='perfil_verificado',
            field=models.BooleanField(default=False, verbose_name='Perfil verificado'),
        ),
        migrations.AddField(
            model_name='perfilempleador',
            name='sitio_web',
            field=models.URLField(blank=True, verbose_name='Sitio web'),
        ),
        migrations.AddField(
            model_name='perfilempleador',
            name='tamaño_organizacion',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 empleados'), ('11-50', '11-50 empleados'), ('51-200', '51-200 empleados'), ('201-500', '201-500 empleados'), ('501-1000', '501-1000 empleados'), ('1000+', 'Más de 1000 empleados'), ('no_aplica', 'No aplica')], max_length=50, verbose_name='Tamaño de la organización'),
        ),
        migrations.AddField(
            model_name='perfilempleador',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='perfilempleador',
            name='contacto_alternativo',
            field=models.CharField(blank=True, help_text='Nombre de persona de contacto', max_length=100, verbose_name='Contacto alternativo'),
        ),
        migrations.AlterField(
            model_name='perfilempleador',
            name='nombre_organizacion',
            field=models.CharField(max_length=200, verbose_name='Nombre de la organización'),
        ),
        migrations.AlterField(
            model_name='perfilempleador',
            name='tipo_entidad',
            field=models.CharField(choices=[('empresa', 'Empresa'), ('fundacion', 'Fundación'), ('organizacion_sin_fines_lucro', 'Organización sin fines de lucro'), ('institucion_educativa', 'Institución educativa'), ('gobierno', 'Gobierno/Institución pública'), ('iglesia', 'Iglesia/Organización religiosa'), ('club_social', 'Club social'), ('restaurante_bar', 'Restaurante/Bar'), ('hotel', 'Hotel/Centro de eventos'), ('particular', 'Particular'), ('otro', 'Otro')], default='empresa', max_length=50, verbose_name='Tipo de entidad'),
        ),
        migrations.AlterField(
            model_name='perfilempleador',
            name='ubicacion',
            field=models.CharField(help_text='Ciudad, región o dirección', max_length=200, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='perfilempleador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empleador', to=settings.AUTH_USER_MODEL),
        ),
    ]
