# Generated by Django 4.2.20 on 2025-08-04 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_perfilempleador_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortafolioMusico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField(blank=True, help_text='Cuéntanos sobre tu trayectoria musical (máx. 1000 caracteres)', max_length=1000)),
                ('instrumento_principal', models.CharField(choices=[('guitarra', 'Guitarra'), ('bajo', 'Bajo'), ('bateria', 'Batería'), ('piano', 'Piano'), ('teclados', 'Teclados'), ('violin', 'Violín'), ('saxofon', 'Saxofón'), ('trompeta', 'Trompeta'), ('flauta', 'Flauta'), ('voz', 'Voz/Canto'), ('armonica', 'Armónica'), ('ukulele', 'Ukulele'), ('mandolina', 'Mandolina'), ('acordeon', 'Acordeón'), ('otro', 'Otro')], default='guitarra', max_length=50, verbose_name='Instrumento principal')),
                ('instrumentos_secundarios', models.CharField(blank=True, help_text='Otros instrumentos que tocas (separados por comas)', max_length=200, verbose_name='Instrumentos secundarios')),
                ('generos_musicales', models.CharField(default='rock', help_text='Géneros musicales que interpretas (separados por comas)', max_length=200, verbose_name='Géneros musicales')),
                ('nivel_experiencia', models.CharField(choices=[('principiante', 'Principiante (0-2 años)'), ('intermedio', 'Intermedio (3-5 años)'), ('avanzado', 'Avanzado (6-10 años)'), ('profesional', 'Profesional (10+ años)')], default='principiante', max_length=20, verbose_name='Nivel de experiencia')),
                ('años_experiencia', models.PositiveIntegerField(default=1, help_text='Número de años tocando música', verbose_name='Años de experiencia')),
                ('formacion_musical', models.TextField(blank=True, help_text='Estudios musicales, cursos, talleres, etc.', max_length=500, verbose_name='Formación musical')),
                ('website_personal', models.URLField(blank=True, verbose_name='Sitio web personal')),
                ('soundcloud_url', models.URLField(blank=True, verbose_name='SoundCloud')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('spotify_url', models.URLField(blank=True, verbose_name='Spotify')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('video_demo', models.URLField(blank=True, help_text='Enlace a video demo (YouTube, Vimeo, etc.)', verbose_name='Video demostración')),
                ('ubicacion', models.CharField(default='No especificada', max_length=100, verbose_name='Ubicación')),
                ('disponible_para_gigs', models.BooleanField(default=True, verbose_name='Disponible para presentaciones')),
                ('tarifa_base', models.PositiveIntegerField(blank=True, help_text='Tarifa base por presentación en pesos chilenos (CLP)', null=True, verbose_name='Tarifa base (CLP)')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('portafolio_publico', models.BooleanField(default=True, help_text='¿Deseas que tu portafolio sea visible públicamente?', verbose_name='Portafolio público')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portafolio_musico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portafolio de Músico',
                'verbose_name_plural': 'Portafolios de Músicos',
            },
        ),
    ]
