# Generated by Django 4.2.20 on 2025-08-04 23:45

from django.db import migrations


def migrar_perfiles_a_portafolios(apps, schema_editor):
    """
    Migra todos los datos profesionales de PerfilMusico a PortafolioMusico
    """
    PerfilMusico = apps.get_model('usuarios', 'PerfilMusico')
    PortafolioMusico = apps.get_model('usuarios', 'PortafolioMusico')
    
    for perfil in PerfilMusico.objects.all():
        # Crear portafolio solo si no existe
        portafolio, created = PortafolioMusico.objects.get_or_create(
            usuario=perfil.usuario,
            defaults={
                'biografia': perfil.biografia or '',
                'instrumento_principal': perfil.instrumento_principal or 'guitarra',
                'instrumentos_secundarios': perfil.instrumentos_secundarios or '',
                'generos_musicales': perfil.generos_musicales or 'rock',
                'nivel_experiencia': perfil.nivel_experiencia or 'principiante',
                'años_experiencia': perfil.años_experiencia or 1,
                'formacion_musical': perfil.formacion_musical or '',
                'website_personal': perfil.website_personal or '',
                'soundcloud_url': perfil.soundcloud_url or '',
                'youtube_url': perfil.youtube_url or '',
                'spotify_url': perfil.spotify_url or '',
                'instagram_url': perfil.instagram_url or '',
                'facebook_url': perfil.facebook_url or '',
                'video_demo': perfil.video_demo or '',
                'ubicacion': perfil.ubicacion or 'No especificada',
                'disponible_para_gigs': perfil.disponible_para_gigs,
                'tarifa_base': perfil.tarifa_base,
                'fecha_creacion': perfil.fecha_creacion,
                'fecha_actualizacion': perfil.fecha_actualizacion,
                'portafolio_publico': perfil.perfil_publico,
            }
        )


def reversar_migracion(apps, schema_editor):
    """
    Función de reversión para la migración
    """
    PortafolioMusico = apps.get_model('usuarios', 'PortafolioMusico')
    PortafolioMusico.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_portafoliomusico'),
    ]

    operations = [
        migrations.RunPython(migrar_perfiles_a_portafolios, reversar_migracion),
    ]
