# Generated by Django 4.2.20 on 2025-08-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_migrar_datos_perfil_a_portafolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilmusico',
            name='años_experiencia',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='disponible_para_gigs',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='formacion_musical',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='generos_musicales',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='instrumento_principal',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='instrumentos_secundarios',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='nivel_experiencia',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='perfil_publico',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='soundcloud_url',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='spotify_url',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='tarifa_base',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='video_demo',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='website_personal',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='contacto_emergencia',
            field=models.CharField(blank=True, help_text='Nombre y teléfono de contacto de emergencia', max_length=100, verbose_name='Contacto de emergencia'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección personal'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='mostrar_telefono_publico',
            field=models.BooleanField(default=False, help_text='¿Permitir que empleadores vean tu teléfono?', verbose_name='Mostrar teléfono públicamente'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='recibir_notificaciones_email',
            field=models.BooleanField(default=True, verbose_name='Recibir notificaciones por email'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono personal', max_length=20, verbose_name='Teléfono'),
        ),
    ]
