# Generated by Django 4.2.20 on 2025-08-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_perfilmusico_años_experiencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilmusico',
            name='contacto_emergencia',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='mostrar_telefono_publico',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='recibir_notificaciones_email',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='telefono',
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='años_experiencia',
            field=models.PositiveIntegerField(default=1, help_text='Número de años tocando música', verbose_name='Años de experiencia'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='biografia',
            field=models.TextField(blank=True, help_text='Cuéntanos sobre tu trayectoria musical (máx. 1000 caracteres)', max_length=1000),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='disponible_para_gigs',
            field=models.BooleanField(default=True, verbose_name='Disponible para presentaciones'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='formacion_musical',
            field=models.TextField(blank=True, help_text='Estudios musicales, cursos, talleres, etc.', max_length=500, verbose_name='Formación musical'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='generos_musicales',
            field=models.CharField(default='rock', help_text='Géneros musicales que interpretas (separados por comas)', max_length=200, verbose_name='Géneros musicales'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='instrumento_principal',
            field=models.CharField(choices=[('guitarra', 'Guitarra'), ('bajo', 'Bajo'), ('bateria', 'Batería'), ('piano', 'Piano'), ('teclados', 'Teclados'), ('violin', 'Violín'), ('saxofon', 'Saxofón'), ('trompeta', 'Trompeta'), ('flauta', 'Flauta'), ('voz', 'Voz/Canto'), ('armonica', 'Armónica'), ('ukulele', 'Ukulele'), ('mandolina', 'Mandolina'), ('acordeon', 'Acordeón'), ('otro', 'Otro')], default='guitarra', max_length=50, verbose_name='Instrumento principal'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='instrumentos_secundarios',
            field=models.CharField(blank=True, help_text='Otros instrumentos que tocas (separados por comas)', max_length=200, verbose_name='Instrumentos secundarios'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='nivel_experiencia',
            field=models.CharField(choices=[('principiante', 'Principiante (0-2 años)'), ('intermedio', 'Intermedio (3-5 años)'), ('avanzado', 'Avanzado (6-10 años)'), ('profesional', 'Profesional (10+ años)')], default='principiante', max_length=20, verbose_name='Nivel de experiencia'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='perfil_publico',
            field=models.BooleanField(default=True, help_text='¿Deseas que tu perfil sea visible públicamente?', verbose_name='Perfil público'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='soundcloud_url',
            field=models.URLField(blank=True, verbose_name='SoundCloud'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='spotify_url',
            field=models.URLField(blank=True, verbose_name='Spotify'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='tarifa_base',
            field=models.PositiveIntegerField(blank=True, help_text='Tarifa base por presentación en pesos chilenos (CLP)', null=True, verbose_name='Tarifa base (CLP)'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='ubicacion',
            field=models.CharField(default='No especificada', max_length=100, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='video_demo',
            field=models.URLField(blank=True, help_text='Enlace a video demo (YouTube, Vimeo, etc.)', verbose_name='Video demostración'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='website_personal',
            field=models.URLField(blank=True, verbose_name='Sitio web personal'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
    ]
