# Generated by Django 4.2.20 on 2025-08-11 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_remove_perfilmusico_contacto_emergencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Género Musical',
                'verbose_name_plural': 'Géneros Musicales',
                'db_table': 'usuarios_generomusical',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('categoria', models.CharField(blank=True, max_length=50, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'db_table': 'usuarios_instrumento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video_youtube', 'Video de YouTube'), ('video_vimeo', 'Video de Vimeo'), ('audio_soundcloud', 'Audio de SoundCloud'), ('audio_spotify', 'Audio de Spotify')], max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, max_length=300, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='portafolios/multimedia/', verbose_name='Imagen')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Multimedia',
                'verbose_name_plural': 'Multimedia',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NivelExperiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(unique=True, verbose_name='Orden')),
                ('años_minimos', models.PositiveIntegerField(default=0, verbose_name='Años mínimos')),
                ('años_maximos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Años máximos')),
            ],
            options={
                'verbose_name': 'Nivel de Experiencia',
                'verbose_name_plural': 'Niveles de Experiencia',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug público')),
                ('biografia', models.TextField(blank=True, help_text='Cuéntanos sobre tu trayectoria musical (máx. 1000 caracteres)', max_length=1000, verbose_name='Biografía profesional')),
                ('formacion_musical', models.TextField(blank=True, help_text='Estudios musicales, cursos, talleres, etc.', max_length=500, verbose_name='Formación musical')),
                ('años_experiencia', models.PositiveIntegerField(default=1, help_text='Número de años tocando música', verbose_name='Años de experiencia')),
                ('website_personal', models.URLField(blank=True, verbose_name='Sitio web personal')),
                ('soundcloud_url', models.URLField(blank=True, verbose_name='SoundCloud')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('spotify_url', models.URLField(blank=True, verbose_name='Spotify')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('video_demo', models.URLField(blank=True, help_text='Enlace a video demo (YouTube, Vimeo, etc.)', verbose_name='Video demostración')),
                ('disponible_para_gigs', models.BooleanField(default=True, verbose_name='Disponible para presentaciones')),
                ('tarifa_base', models.PositiveIntegerField(blank=True, help_text='Tarifa base por presentación en pesos chilenos (CLP)', null=True, verbose_name='Tarifa base (CLP)')),
                ('show_email', models.BooleanField(default=False, verbose_name='Mostrar email')),
                ('show_social_links', models.BooleanField(default=True, verbose_name='Mostrar enlaces sociales')),
                ('show_education', models.BooleanField(default=True, verbose_name='Mostrar formación')),
                ('show_tarifa', models.BooleanField(default=True, verbose_name='Mostrar tarifa')),
                ('show_telefono', models.BooleanField(default=False, verbose_name='Mostrar teléfono')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Portafolio activo')),
                ('nivel_experiencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.nivelexperiencia', verbose_name='Nivel de experiencia')),
            ],
            options={
                'verbose_name': 'Portafolio',
                'verbose_name_plural': 'Portafolios',
            },
        ),
        migrations.CreateModel(
            name='PortafolioGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.PositiveIntegerField(default=1, verbose_name='Prioridad')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.genero')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portafolio_generos', to='usuarios.portafolio')),
            ],
            options={
                'verbose_name': 'Género del Portafolio',
                'verbose_name_plural': 'Géneros del Portafolio',
                'ordering': ['prioridad'],
                'unique_together': {('portafolio', 'genero')},
            },
        ),
        migrations.CreateModel(
            name='PortafolioInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Es instrumento principal')),
                ('prioridad', models.PositiveIntegerField(default=1, verbose_name='Prioridad')),
                ('años_experiencia', models.PositiveIntegerField(blank=True, null=True, verbose_name='Años de experiencia con este instrumento')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.instrumento')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portafolio_instrumentos', to='usuarios.portafolio')),
            ],
            options={
                'verbose_name': 'Instrumento del Portafolio',
                'verbose_name_plural': 'Instrumentos del Portafolio',
                'ordering': ['prioridad', '-es_principal'],
                'unique_together': {('portafolio', 'instrumento')},
            },
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_nombre', models.CharField(max_length=100, verbose_name='Nombre del autor')),
                ('texto', models.TextField(max_length=500, verbose_name='Testimonio')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('verificado', models.BooleanField(default=False, verbose_name='Verificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('autor_usuario', models.ForeignKey(blank=True, help_text='Si el testimonio es de un usuario registrado', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario autor (opcional)')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonios', to='usuarios.portafolio')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('region', models.CharField(blank=True, max_length=50, verbose_name='Región')),
                ('pais', models.CharField(default='Chile', max_length=50, verbose_name='País')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['orden', 'region', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='años_experiencia',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='disponible_para_gigs',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='formacion_musical',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='generos_musicales',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='instrumento_principal',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='instrumentos_secundarios',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='nivel_experiencia',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='perfil_publico',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='soundcloud_url',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='spotify_url',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='tarifa_base',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='video_demo',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='website_personal',
        ),
        migrations.RemoveField(
            model_name='perfilmusico',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contacto de emergencia'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='mostrar_telefono_publico',
            field=models.BooleanField(default=False, verbose_name='Mostrar teléfono públicamente'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='recibir_notificaciones_email',
            field=models.BooleanField(default=True, verbose_name='Recibir notificaciones por email'),
        ),
        migrations.AddField(
            model_name='perfilmusico',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.DeleteModel(
            name='PortafolioMusico',
        ),
        migrations.AddField(
            model_name='portafolio',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.ubicacion', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='portafolio',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portafolio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='portafolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='usuarios.portafolio'),
        ),
    ]
