# Generated by Django 4.2.20 on 2025-08-12 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_genero_instrumento_multimedia_nivelexperiencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilmusico',
            name='contacto_emergencia',
        ),
    ]
