# Generated by Django 4.2.20 on 2025-08-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_eliminar_contacto_emergencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={'ordering': ['nombre'], 'verbose_name': 'Género Musical', 'verbose_name_plural': 'Géneros Musicales'},
        ),
        migrations.AlterModelOptions(
            name='instrumento',
            options={'ordering': ['categoria', 'nombre'], 'verbose_name': 'Instrumento', 'verbose_name_plural': 'Instrumentos'},
        ),
    ]
