# Generated by Django 4.2.20 on 2025-08-14 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_genero_options_alter_instrumento_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug público')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la oferta')),
                ('descripcion', models.TextField(help_text='Describe la oportunidad laboral (máx. 2000 caracteres)', max_length=2000, verbose_name='Descripción detallada')),
                ('requisitos', models.TextField(blank=True, help_text='Requisitos técnicos y experiencia requerida', max_length=1000, verbose_name='Requisitos específicos')),
                ('tipo_contrato', models.CharField(choices=[('evento_unico', 'Evento único'), ('contrato_temporal', 'Contrato temporal'), ('contrato_indefinido', 'Contrato indefinido'), ('freelance', 'Freelance'), ('colaboracion', 'Colaboración')], max_length=30, verbose_name='Tipo de contrato')),
                ('fecha_evento', models.DateTimeField(blank=True, help_text='Para eventos únicos, fecha y hora específica', null=True, verbose_name='Fecha del evento')),
                ('duracion_estimada', models.CharField(blank=True, help_text='Ej: 3 horas, 2 días, 1 mes', max_length=100, verbose_name='Duración estimada')),
                ('presupuesto_minimo', models.PositiveIntegerField(blank=True, help_text='Presupuesto mínimo ofrecido en pesos chilenos', null=True, verbose_name='Presupuesto mínimo (CLP)')),
                ('presupuesto_maximo', models.PositiveIntegerField(blank=True, help_text='Presupuesto máximo disponible en pesos chilenos', null=True, verbose_name='Presupuesto máximo (CLP)')),
                ('presupuesto_a_convenir', models.BooleanField(default=False, verbose_name='Presupuesto a convenir')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20, verbose_name='Estado de la oferta')),
                ('cupos_disponibles', models.PositiveIntegerField(default=1, verbose_name='Número de cupos disponibles')),
                ('fecha_limite_postulacion', models.DateTimeField(blank=True, help_text='Fecha límite para recibir postulaciones', null=True, verbose_name='Fecha límite para postular')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('empleador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_laborales', to='usuarios.perfilempleador', verbose_name='Empleador')),
                ('nivel_experiencia_minimo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.nivelexperiencia', verbose_name='Nivel de experiencia mínimo requerido')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.ubicacion', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Oferta Laboral',
                'verbose_name_plural': 'Ofertas Laborales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'managed': False, 'ordering': ['nombre'], 'verbose_name': 'Género Musical', 'verbose_name_plural': 'Géneros Musicales'},
        ),
        migrations.AlterModelOptions(
            name='instrumento',
            options={'managed': False, 'ordering': ['categoria', 'nombre'], 'verbose_name': 'Instrumento', 'verbose_name_plural': 'Instrumentos'},
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_postulacion', models.CharField(choices=[('espontanea', 'Postulación espontánea'), ('invitacion', 'Invitación directa')], default='espontanea', max_length=20, verbose_name='Tipo de postulación')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('en_revision', 'En revisión'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada por el músico')], default='pendiente', max_length=20, verbose_name='Estado de la postulación')),
                ('mensaje_personalizado', models.TextField(blank=True, help_text='Mensaje opcional para el empleador (máx. 1000 caracteres)', max_length=1000, verbose_name='Mensaje personalizado')),
                ('tarifa_propuesta', models.PositiveIntegerField(blank=True, help_text='Tarifa propuesta por el músico en pesos chilenos', null=True, verbose_name='Tarifa propuesta (CLP)')),
                ('fecha_postulacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de postulación')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta del empleador')),
                ('notas_empleador', models.TextField(blank=True, help_text='Comentarios internos del empleador sobre la postulación', max_length=500, verbose_name='Notas del empleador')),
                ('musico', models.ForeignKey(limit_choices_to={'tipo_usuario': 'musico'}, on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to=settings.AUTH_USER_MODEL, verbose_name='Músico')),
                ('oferta_laboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='usuarios.ofertalaboral', verbose_name='Oferta laboral')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='usuarios.portafolio', verbose_name='Portafolio utilizado')),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'ordering': ['-fecha_postulacion'],
                'unique_together': {('oferta_laboral', 'musico')},
            },
        ),
        migrations.CreateModel(
            name='OfertaInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_obligatorio', models.BooleanField(default=True, help_text='Si es obligatorio o solo deseable', verbose_name='Es obligatorio')),
                ('prioridad', models.PositiveIntegerField(default=1, verbose_name='Prioridad')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.instrumento')),
                ('oferta_laboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferta_instrumentos', to='usuarios.ofertalaboral')),
            ],
            options={
                'verbose_name': 'Instrumento de la Oferta',
                'verbose_name_plural': 'Instrumentos de la Oferta',
                'ordering': ['prioridad', '-es_obligatorio'],
                'unique_together': {('oferta_laboral', 'instrumento')},
            },
        ),
        migrations.CreateModel(
            name='OfertaGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.PositiveIntegerField(default=1, verbose_name='Prioridad')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.genero')),
                ('oferta_laboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferta_generos', to='usuarios.ofertalaboral')),
            ],
            options={
                'verbose_name': 'Género de la Oferta',
                'verbose_name_plural': 'Géneros de la Oferta',
                'ordering': ['prioridad'],
                'unique_together': {('oferta_laboral', 'genero')},
            },
        ),
    ]
