# Generated by Django 4.2.20 on 2025-08-19 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_agregar_sistema_ofertas_laborales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='nivel_experiencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.nivelexperiencia', verbose_name='Nivel de experiencia'),
        ),
    ]
