# Generated by Django 4.2.20 on 2025-08-19 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_alter_portafolio_nivel_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertalaboral',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.ubicacion', verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.ubicacion', verbose_name='Ubicación'),
        ),
    ]
