# Generated by Django 4.2.20 on 2025-08-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_ofertalaboral_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={'managed': True, 'ordering': ['nombre'], 'verbose_name': 'Género Musical', 'verbose_name_plural': 'Géneros Musicales'},
        ),
        migrations.AlterModelOptions(
            name='instrumento',
            options={'managed': True, 'ordering': ['categoria', 'nombre'], 'verbose_name': 'Instrumento', 'verbose_name_plural': 'Instrumentos'},
        ),
    ]
