# Generated by Django 4.2.20 on 2025-08-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_alter_genero_options_alter_instrumento_options'),
    ]

    operations = [
    ]
