# Generated by Django 4.2.20 on 2025-08-19 17:39

from django.db import migrations


def crear_tablas_catalogos(apps, schema_editor):
    """Crear tablas de catálogos que no se crearon por managed=False"""
    db_alias = schema_editor.connection.alias
    
    with schema_editor.connection.cursor() as cursor:
        # Crear tabla usuarios_instrumento si no existe
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS usuarios_instrumento (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                nombre VARCHAR(50) NOT NULL UNIQUE,
                categoria VARCHAR(50)
            );
        """)
        
        # Crear tabla usuarios_generomusical si no existe
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS usuarios_generomusical (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                nombre VARCHAR(50) NOT NULL UNIQUE,
                descripcion TEXT
            );
        """)


def poblar_datos_iniciales(apps, schema_editor):
    """Insertar datos iniciales necesarios para el funcionamiento"""
    db_alias = schema_editor.connection.alias
    
    with schema_editor.connection.cursor() as cursor:
        # Insertar instrumentos básicos
        cursor.execute("""
            INSERT OR IGNORE INTO usuarios_instrumento (nombre, categoria) VALUES 
            ('Guitarra', 'Cuerdas'),
            ('Piano', 'Teclas'),
            ('Batería', 'Percusión'),
            ('Bajo', 'Cuerdas'),
            ('Violín', 'Cuerdas'),
            ('Saxofón', 'Viento'),
            ('Trompeta', 'Viento'),
            ('Flauta', 'Viento'),
            ('Violonchelo', 'Cuerdas'),
            ('Teclado', 'Teclas');
        """)
        
        # Insertar géneros musicales básicos
        cursor.execute("""
            INSERT OR IGNORE INTO usuarios_generomusical (nombre, descripcion) VALUES 
            ('Rock', 'Música rock'),
            ('Jazz', 'Música jazz'),
            ('Pop', 'Música pop'),
            ('Clásica', 'Música clásica'),
            ('Folk', 'Música folk'),
            ('Blues', 'Música blues'),
            ('Reggae', 'Música reggae'),
            ('Electronic', 'Música electrónica'),
            ('Country', 'Música country'),
            ('R&B', 'Rhythm and Blues');
        """)
        
        # Insertar niveles de experiencia si no existen
        cursor.execute("""
            INSERT OR IGNORE INTO usuarios_nivelexperiencia (nombre, descripcion, orden, años_minimos, años_maximos) VALUES 
            ('Principiante', 'De 0 a 2 años de experiencia', 1, 0, 2),
            ('Intermedio', 'De 3 a 5 años de experiencia', 2, 3, 5),
            ('Avanzado', 'De 6 a 10 años de experiencia', 3, 6, 10),
            ('Profesional', 'Más de 10 años de experiencia', 4, 10, NULL);
        """)
        
        # Insertar ubicaciones completas de Chile (Regiones y Comunas principales)
        cursor.execute("""
            INSERT OR IGNORE INTO usuarios_ubicacion (nombre, region, pais, activo, orden) VALUES 
            -- Región de Arica y Parinacota
            ('Arica', 'Arica y Parinacota', 'Chile', 1, 1),
            ('Putre', 'Arica y Parinacota', 'Chile', 1, 2),
            
            -- Región de Tarapacá
            ('Iquique', 'Tarapacá', 'Chile', 1, 3),
            ('Alto Hospicio', 'Tarapacá', 'Chile', 1, 4),
            ('Pozo Almonte', 'Tarapacá', 'Chile', 1, 5),
            
            -- Región de Antofagasta
            ('Antofagasta', 'Antofagasta', 'Chile', 1, 6),
            ('Calama', 'Antofagasta', 'Chile', 1, 7),
            ('Tocopilla', 'Antofagasta', 'Chile', 1, 8),
            ('Mejillones', 'Antofagasta', 'Chile', 1, 9),
            
            -- Región de Atacama
            ('Copiapó', 'Atacama', 'Chile', 1, 10),
            ('Vallenar', 'Atacama', 'Chile', 1, 11),
            ('Chañaral', 'Atacama', 'Chile', 1, 12),
            
            -- Región de Coquimbo
            ('La Serena', 'Coquimbo', 'Chile', 1, 13),
            ('Coquimbo', 'Coquimbo', 'Chile', 1, 14),
            ('Ovalle', 'Coquimbo', 'Chile', 1, 15),
            ('Illapel', 'Coquimbo', 'Chile', 1, 16),
            ('Vicuña', 'Coquimbo', 'Chile', 1, 17),
            
            -- Región de Valparaíso
            ('Valparaíso', 'Valparaíso', 'Chile', 1, 18),
            ('Viña del Mar', 'Valparaíso', 'Chile', 1, 19),
            ('Quilpué', 'Valparaíso', 'Chile', 1, 20),
            ('Villa Alemana', 'Valparaíso', 'Chile', 1, 21),
            ('San Antonio', 'Valparaíso', 'Chile', 1, 22),
            ('Quillota', 'Valparaíso', 'Chile', 1, 23),
            ('Los Andes', 'Valparaíso', 'Chile', 1, 24),
            ('San Felipe', 'Valparaíso', 'Chile', 1, 25),
            ('Casablanca', 'Valparaíso', 'Chile', 1, 26),
            
            -- Región Metropolitana
            ('Santiago', 'Metropolitana', 'Chile', 1, 27),
            ('Las Condes', 'Metropolitana', 'Chile', 1, 28),
            ('Providencia', 'Metropolitana', 'Chile', 1, 29),
            ('Ñuñoa', 'Metropolitana', 'Chile', 1, 30),
            ('La Reina', 'Metropolitana', 'Chile', 1, 31),
            ('Vitacura', 'Metropolitana', 'Chile', 1, 32),
            ('Lo Barnechea', 'Metropolitana', 'Chile', 1, 33),
            ('Maipú', 'Metropolitana', 'Chile', 1, 34),
            ('Puente Alto', 'Metropolitana', 'Chile', 1, 35),
            ('La Florida', 'Metropolitana', 'Chile', 1, 36),
            ('Peñalolén', 'Metropolitana', 'Chile', 1, 37),
            ('San Bernardo', 'Metropolitana', 'Chile', 1, 38),
            ('Melipilla', 'Metropolitana', 'Chile', 1, 39),
            ('Talagante', 'Metropolitana', 'Chile', 1, 40),
            
            -- Región del Libertador Bernardo O''Higgins
            ('Rancagua', 'O''Higgins', 'Chile', 1, 41),
            ('San Fernando', 'O''Higgins', 'Chile', 1, 42),
            ('Rengo', 'O''Higgins', 'Chile', 1, 43),
            ('Machalí', 'O''Higgins', 'Chile', 1, 44),
            ('Santa Cruz', 'O''Higgins', 'Chile', 1, 45),
            
            -- Región del Maule
            ('Talca', 'Maule', 'Chile', 1, 46),
            ('Curicó', 'Maule', 'Chile', 1, 47),
            ('Linares', 'Maule', 'Chile', 1, 48),
            ('Cauquenes', 'Maule', 'Chile', 1, 49),
            ('Constitución', 'Maule', 'Chile', 1, 50),
            
            -- Región de Ñuble
            ('Chillán', 'Ñuble', 'Chile', 1, 51),
            ('San Carlos', 'Ñuble', 'Chile', 1, 52),
            ('Bulnes', 'Ñuble', 'Chile', 1, 53),
            
            -- Región del Biobío
            ('Concepción', 'Biobío', 'Chile', 1, 54),
            ('Talcahuano', 'Biobío', 'Chile', 1, 55),
            ('Chiguayante', 'Biobío', 'Chile', 1, 56),
            ('San Pedro de la Paz', 'Biobío', 'Chile', 1, 57),
            ('Hualpén', 'Biobío', 'Chile', 1, 58),
            ('Los Ángeles', 'Biobío', 'Chile', 1, 59),
            ('Coronel', 'Biobío', 'Chile', 1, 60),
            ('Lota', 'Biobío', 'Chile', 1, 61),
            
            -- Región de La Araucanía
            ('Temuco', 'La Araucanía', 'Chile', 1, 62),
            ('Padre Las Casas', 'La Araucanía', 'Chile', 1, 63),
            ('Villarrica', 'La Araucanía', 'Chile', 1, 64),
            ('Pucón', 'La Araucanía', 'Chile', 1, 65),
            ('Angol', 'La Araucanía', 'Chile', 1, 66),
            
            -- Región de Los Ríos
            ('Valdivia', 'Los Ríos', 'Chile', 1, 67),
            ('La Unión', 'Los Ríos', 'Chile', 1, 68),
            ('Río Bueno', 'Los Ríos', 'Chile', 1, 69),
            
            -- Región de Los Lagos
            ('Puerto Montt', 'Los Lagos', 'Chile', 1, 70),
            ('Osorno', 'Los Lagos', 'Chile', 1, 71),
            ('Castro', 'Los Lagos', 'Chile', 1, 72),
            ('Ancud', 'Los Lagos', 'Chile', 1, 73),
            ('Puerto Varas', 'Los Lagos', 'Chile', 1, 74),
            
            -- Región de Aysén
            ('Coyhaique', 'Aysén', 'Chile', 1, 75),
            ('Puerto Aysén', 'Aysén', 'Chile', 1, 76),
            ('Chile Chico', 'Aysén', 'Chile', 1, 77),
            
            -- Región de Magallanes
            ('Punta Arenas', 'Magallanes', 'Chile', 1, 78),
            ('Puerto Natales', 'Magallanes', 'Chile', 1, 79),
            ('Porvenir', 'Magallanes', 'Chile', 1, 80);
        """)


def reversar_cambios(apps, schema_editor):
    """Reversar los cambios si es necesario"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_auto_20250819_1338'),
    ]

    operations = [
        migrations.RunPython(crear_tablas_catalogos, reversar_cambios),
        migrations.RunPython(poblar_datos_iniciales, reversar_cambios),
    ]
