# Generated by Django 4.2.20 on 2025-08-25 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('postulacion_cancelada', 'Postulación cancelada'), ('oferta_completada', 'Oferta completada'), ('invitacion_aceptada', 'Invitación aceptada'), ('invitacion_rechazada', 'Invitación rechazada'), ('invitacion_expirada', 'Invitación expirada')], max_length=25, verbose_name='Tipo de notificación'),
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de respuesta'), ('aceptada', 'Aceptada (crea postulación)'), ('rechazada', 'Rechazada por el músico'), ('expirada', 'Expirada sin respuesta'), ('cancelada', 'Cancelada por el empleador')], default='pendiente', max_length=20, verbose_name='Estado de la invitación')),
                ('mensaje_invitacion', models.TextField(help_text='Mensaje personalizado del empleador al músico (máx. 1000 caracteres)', max_length=1000, verbose_name='Mensaje de invitación')),
                ('tarifa_ofrecida', models.PositiveIntegerField(blank=True, help_text='Tarifa propuesta por el empleador en pesos chilenos', null=True, verbose_name='Tarifa ofrecida (CLP)')),
                ('fecha_invitacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de invitación')),
                ('fecha_expiracion', models.DateTimeField(help_text='Fecha límite para que el músico responda', verbose_name='Fecha de expiración')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta del músico')),
                ('mensaje_respuesta', models.TextField(blank=True, help_text='Mensaje opcional del músico al responder (máx. 500 caracteres)', max_length=500, verbose_name='Mensaje de respuesta del músico')),
                ('empleador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_enviadas', to='usuarios.perfilempleador', verbose_name='Empleador que invita')),
                ('musico', models.ForeignKey(limit_choices_to={'tipo_usuario': 'musico'}, on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Músico invitado')),
                ('oferta_laboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='usuarios.ofertalaboral', verbose_name='Oferta laboral')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='usuarios.portafolio', verbose_name='Portafolio que motivó la invitación')),
                ('postulacion_creada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitacion_origen', to='usuarios.postulacion', verbose_name='Postulación creada')),
            ],
            options={
                'verbose_name': 'Invitación',
                'verbose_name_plural': 'Invitaciones',
                'ordering': ['-fecha_invitacion'],
            },
        ),
        migrations.AddField(
            model_name='notificacion',
            name='invitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='usuarios.invitacion', verbose_name='Invitación relacionada'),
        ),
        migrations.AddIndex(
            model_name='invitacion',
            index=models.Index(fields=['estado', 'fecha_expiracion'], name='usuarios_in_estado_1a31e8_idx'),
        ),
        migrations.AddIndex(
            model_name='invitacion',
            index=models.Index(fields=['musico', 'estado'], name='usuarios_in_musico__fa94b8_idx'),
        ),
        migrations.AddIndex(
            model_name='invitacion',
            index=models.Index(fields=['empleador', 'estado'], name='usuarios_in_emplead_0d6ade_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invitacion',
            unique_together={('oferta_laboral', 'musico')},
        ),
    ]
