# Generated by Django 4.2.20 on 2025-08-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_add_invitacion_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='show_education',
            field=models.BooleanField(default=True, help_text='Muestra tu formación y estudios musicales', verbose_name='Mostrar formación musical'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='show_email',
            field=models.BooleanField(default=False, help_text='Permite que visitantes vean tu email en el portafolio público', verbose_name='Mostrar email público'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='show_social_links',
            field=models.BooleanField(default=True, help_text='Muestra tus redes sociales y sitio web', verbose_name='Mostrar enlaces sociales'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='show_tarifa',
            field=models.BooleanField(default=True, help_text='Permite que se vea tu tarifa en el portafolio', verbose_name='Mostrar tarifa base'),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='show_telefono',
            field=models.BooleanField(default=False, help_text='Permite que visitantes vean tu teléfono en el portafolio público', verbose_name='Mostrar teléfono público'),
        ),
    ]
