# Generated by Django 4.2.20 on 2025-08-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_alter_portafolio_show_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='autor_cargo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo/Posición del autor'),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='autor_email',
            field=models.EmailField(blank=True, help_text='Para solicitudes de referencia', max_length=254, verbose_name='Email del autor'),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='autor_organizacion',
            field=models.CharField(blank=True, max_length=150, verbose_name='Organización/Empresa'),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='duracion_colaboracion',
            field=models.CharField(blank=True, help_text='Ej: 3 meses, 1 año, evento único', max_length=100, verbose_name='Duración de la colaboración'),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobado', 'Aprobado y visible'), ('rechazado', 'Rechazado'), ('directo', 'Agregado directamente')], default='directo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='fecha_fin_colaboracion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha fin colaboración'),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='fecha_inicio_colaboracion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha inicio colaboración'),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta'),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='fecha_solicitud',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de solicitud'),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='mensaje_solicitud',
            field=models.TextField(blank=True, help_text='Mensaje personalizado del músico al solicitar la referencia', max_length=300, verbose_name='Mensaje de solicitud'),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='proyecto_evento',
            field=models.CharField(blank=True, help_text='Nombre del proyecto, evento o colaboración', max_length=200, verbose_name='Proyecto/Evento'),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='tipo',
            field=models.CharField(choices=[('referencia_laboral', 'Referencia laboral'), ('testimonio_cliente', 'Testimonio de cliente'), ('recomendacion_general', 'Recomendación general')], default='testimonio_cliente', max_length=30, verbose_name='Tipo de testimonio'),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='token_solicitud',
            field=models.CharField(blank=True, help_text='Token único para links de aprobación', max_length=64, verbose_name='Token de solicitud'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='texto',
            field=models.TextField(max_length=500, verbose_name='Testimonio/Referencia'),
        ),
        migrations.AddIndex(
            model_name='testimonio',
            index=models.Index(fields=['estado'], name='usuarios_te_estado_827c57_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonio',
            index=models.Index(fields=['token_solicitud'], name='usuarios_te_token_s_09b623_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonio',
            index=models.Index(fields=['tipo'], name='usuarios_te_tipo_cdf33e_idx'),
        ),
    ]
