# Generated by Django 4.2.20 on 2025-09-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_ticket_4_1_sistema_referencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('nueva_postulacion', 'Nueva postulación'), ('postulacion_cancelada', 'Postulación cancelada'), ('oferta_completada', 'Oferta completada'), ('invitacion_aceptada', 'Invitación aceptada'), ('invitacion_rechazada', 'Invitación rechazada'), ('invitacion_expirada', 'Invitación expirada')], max_length=25, verbose_name='Tipo de notificación'),
        ),
    ]
